# Define a method display_board that prints a 3x3 Tic Tac Toe Board
def display_board
  #puts "A Tic Tac Toe Board"
  print "   "
  print "|"
  print "   "
  print "|"
  puts "   "
  puts "-----------"
  print "   "
  print "|"
  print "   "
  print "|"
  puts "   "
  puts "-----------"
  print "   "
  print "|"
  print "   "
  print "|"
  puts "   "
end
