# Define a method display_board that prints a 3x3 Tic Tac Toe Board
def display_board
  row = ["   ", "|", "   ", "|", "   "]
  print row[0]
  print row[1]
  print row[2]
  print row[3]
  puts row[4]
  dash_line = ["-----------"]
  puts dash_line[0]
  row1 = ["   ", "|", "   ", "|", "   "]
  print row1[0]
  print row1[1]
  print row1[2]
  print row1[3]
  puts row1[4]
  puts dash_line[0]
  row2 = ["   ", "|", "   ", "|", "   "]
  print row2[0]
  print row2[1]
  print row2[2]
  print row2[3]
  puts row2[4]
  end
